### ISSUE TITLE
Cover system - status effect implementation - QoL feature

### ISSUE THREAD

**Issue by JohnnyShootos** [moo-man/ImpMal-FoundryVTT#15]
Hi there, first of all thank you for your hard work.

It would be amazing if there was a Status Effect added for Light, Medium and Heavy Cover that would increase the character armor in all locations by +2 / +4 / +6 respectively as per the core rules. 

Perhaps it could have 3 boxes next to it similar to the other status effects so that players can manually toggle their cover, as well as have 3 little icons on the token itself to add the different levels of cover. Cover bonuses should not be able to stack.

It may be best however, to have the cover type switchable from the "Combat" tab of the actor sheet? That way it saves a player having to switch between tabs as often?

The reason im requesting this feature is so that the automatic application of damage from the combat rolls in the chat bar takes the cover amount into account when calculating damage applied.

**Comment by moo-man** [comment]
Cover is already implemented via zones, or am I missing something?

**Comment by JohnnyShootos** [comment]
apologies - it took me a while to find how to create zones and set their attributes. 

I have found that now and we can close this.
