### ISSUE TITLE
Roles seem to be bugged in character creation.

### ISSUE THREAD

**Issue by Arcogovion** [moo-man/ImpMal-FoundryVTT#25]
I was making a character for a campaign and noticed that the talents given by their role were taking away from the character EXP pool, this included advances and so on. I dived into it to try and see if it was a problem on my end and discovered that the role talent trees were blank, they were not displaying any names.

I had guessed that when the role was inserted into the character sheet the user was meant to be prompted with the choices of what advancements they will take and so on, but even if that were not the case, at least on my end, the roles seem to be totally broken.

I have tried this on both versions of foundry. v11 and v12.

**Screenshots**
![image](https://github.com/user-attachments/assets/6cff36ae-3ca1-44c2-8990-61f7add97648)

**Version Numbers**
Tested on both v11 and v12 Build 330.
This is using Imperium Maledictum 1.3.1
There were no extra modules installed outside the Core Rulebook Module.
![image](https://github.com/user-attachments/assets/e841cba5-ebc2-41f5-bee5-e3e5d9d3c58e)

**Comment by moo-man** [comment]
I believe this is resolve, but if not, please reopen.
