### ISSUE TITLE
Overwriting Origin + Role does not work

### ISSUE THREAD

**Issue by Stexinator** [moo-man/ImpMal-FoundryVTT#29]
**Describe the bug**
Sometimes adding a role, after another role was added does not work

**To Reproduce**
- Create blank character
- add a role
- add another role
- delete role
- add role => error

The problem seems to be fixable when the first role is applied again and then deleted

**Version Numbers**
Version Numbers
Foundry v12
IM 1.3.1

**Comment by moo-man** [comment]
Cannot reproduce this, is this still an issue?

**Comment by Stexinator** [comment]
Tested it and it is fixed in 2.0.1
