### ISSUE TITLE
Impossible to load scene

### ISSUE THREAD

**Issue by MatthieuMarino** [moo-man/ImpMal-FoundryVTT#3]
When I activate a scene, the loading stop at 56% and hang. Only fix is to reload foundry is safe launch mod which disable all modules.
The scene is a default scene with a background image jpg hosted on my foundry server. No other setting was modified apart from load an image as background.
I can properly use the warhammer fantasy version of your system on the same setup.

Foundry infos : 
Foundry Virtual Tabletop: Version 11 Stable, 11.315
Game System: impmal, 1.0.1
Active Modules: 2
Performance Mode: 2

OS: Windows NT 10.0; Win64; x64
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0
GPU: ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Max Texture Size: 16384

No viewed scene

Actors: 4 | Items: 15 | Journal Entries: 0 | Rollable Tables: 0 |
Playlists: 7 | Compendium Packs: 1 | Chat Messages: 20

**Comment by moo-man** [comment]
Use any other browser and it will work in the meantime.

**Comment by moo-man** [comment]
Closed via #4
