### ISSUE TITLE
Origin/Faction/Role from existing characters vanished

### ISSUE THREAD

**Issue by Stexinator** [moo-man/ImpMal-FoundryVTT#34]
**Describe the bug**
Origin/Faction/Role from existing characters vanished. The character I created yesterday with the generator does not have this problem

**To Reproduce**
Dont know if it is reproducable anymore. If you want an export write me on Discord

**Screenshots**
![grafik](https://github.com/user-attachments/assets/c70b7dd0-ea5d-4b3b-a5f1-cfa0c4194974)

**Version Numbers**
ImpMal 2.0.1

**Comment by moo-man** [comment]
Fixed via https://github.com/moo-man/WarhammerLibrary-FVTT/commit/571e4e949de1d0c1f08b487b97bd7b4385bdbfcf
