### ISSUE TITLE
Patron and Character Form Issues (missing drop-downs and lack of field persistence)

### ISSUE THREAD

**Issue by aaron-bigadventurecrew** [moo-man/ImpMal-FoundryVTT#37]
**Describe the bug**
Not able to have certain Patron or Character form fields persist, i.e. Patron Faction or Character Role.

**To Reproduce**
Attempt to fully create a Patron or Character in full with all fields persisting after closing.

**Screenshots**
GIF, HARs, and Browser Console Logs attached

**Version Numbers**
Have reproduced with Win 10 Pro and Debian 12 NodeJS hosts using these versions:
Foundry 12.331 and 12.324
Imperium Maledictum Game System 2.0.0 and 2.0.2
Imperium Maledictum: Core Rulebook 2.0.0
Warhammer Library 1.2.1
(Optionally with/without impmal-combat-resolve Add-On)
And every combination thereof

On Windows I used the EXE installers from Foundry's site then intra-Foundry installed the Game System/Modules.

In AWS EC2 Debian 12:
###Spin up EC2 Debian 12 HVM 64-bit (x86) instance on t2.micro
###Copy Timed URL download link from Foundry
sudo apt update && sudo apt upgrade
sudo apt install -y libssl-dev curl unzip
curl -sL https://deb.nodesource.com/setup_20.x | sudo bash -
sudo apt install -y nodejs
mkdir foundryvtt
mkdir foundrydata
cd foundryvtt
curl -O https://r2.foundryvtt.com/releases/12.331/FoundryVTT-12.331.zip?verify=$REDACTED
unzip foundryvtt.zip
node resources/app/main.js --dataPath=$HOME/foundrydata
###Activate with license key, install Game System and Add-Ons, create World

**Attachments**
[DebImpMalPatronIssue.log](https://github.com/user-attachments/files/17581895/DebImpMalPatronIssue.log)
[WinImpMalPatronIssue.log](https://github.com/user-attachments/files/17581896/WinImpMalPatronIssue.log)
[DebImpMalPatronIssue.har.txt](https://github.com/user-attachments/files/17581897/DebImpMalPatronIssue.har.txt)
[WinImpMalPatronIssue.har.txt](https://github.com/user-attachments/files/17581898/WinImpMalPatronIssue.har.txt)
![ImpMalPatronIssue](https://github.com/user-attachments/assets/6d6cd0b9-401f-49cf-b81e-773fc3b37a3c)

**Comment by aaron-bigadventurecrew** [comment]
I bought this from Cubicle 7 who I think the maintainer is associated with when looking at the system.json info:
https://cubicle7games.com/warhammer-40-000-roleplay-imperium-maledictum-foundry-core-module
https://foundryvtt.com/packages/impmal-core/

Which is intended to work with conjunction with this Game System:
https://foundryvtt.com/packages/impmal

Is there a LTS version combination I can revert to just so things work as intended?

**Comment by moo-man** [comment]
You can install version [1.3.1](https://raw.githubusercontent.com/moo-man/ImpMal-FoundryVTT/1.3.1/system.json), which should work (disable the Warhammer Library module if doing so).

**Comment by aaron-bigadventurecrew** [comment]
Finally, the Game System itself gives these warnings:

System "impmal" defines ChatMessage document sub-type "base" which is a reserved core type.
The "Warhammer 40,000: Imperium Maledictum" system's manifest contained the following unknown keys: "templateVersion"

And the Combat Resolve Add-On gives this (hence trying each permutation with/without it as well):
The "Imperium Maledictum - Combat Resolve" module's manifest contained the following unknown keys: "system"

**Comment by aaron-bigadventurecrew** [comment]
> You can install version [1.3.1](https://raw.githubusercontent.com/moo-man/ImpMal-FoundryVTT/1.3.1/system.json), which should work (disable the Warhammer Library module if doing so).

Will try now, report back in just a few mins

**Comment by moo-man** [comment]
Also, you can give them the actual Faction item, and it will reflect properly. 

Fixed in https://github.com/moo-man/WarhammerLibrary-FVTT/commit/6f25fdcba6a666e0a758d19aede9ca5ae9f83969

**Comment by aaron-bigadventurecrew** [comment]
Just tested with the Core Rulebook 1.0.3 and Game System 1.3.1 which appears to address the initially reported issues.

When you say "Also, you can give them the actual Faction item, and it will reflect properly" what do you mean? Like the UUID of a Faction? The only entry is a String AFAIK when we were testing it doing Session 0 stuff tonight. I'm more of a backend/infra guy but one of my players is a frontend/analytics/JS guy can couldn't figure out the issue either.

**Comment by aaron-bigadventurecrew** [comment]
Also by marking this as Completed are you affirming that Core Rulebook 1.0.3 / Game System 1.3.1 is the Stable version at this time? Nothing in 2.x.x seems to work as intended in full, which is fine if we weren't defaulted to it in Foundry until it's ready. Is there any other documentation specific to this Game System or is it just a matter of perusing this repo on a code level?

**Comment by moo-man** [comment]
If you add a Faction item to the actor, it will use the name of that Item. It won't be an input anymore, and you can delete the item with the X next to it. 
![image](https://github.com/user-attachments/assets/0c4b7ecf-4619-4b82-be68-ac3abc4b7c50)

Yes the 1.x.x series is intended for V11 (but compatible with V12) and has been stable for a while. The 2.x.x version is intended for V12 and integrates the shared Warhammer Library, but has caused more problems than I anticipated.

**Comment by aaron-bigadventurecrew** [comment]
Thanks for the update, we'll use this version combo for our upcoming 8-12 session campaign to give 2.x.x time to bake. If you ever need live/prod analytics of 2.x.x stuff let me know and I can give you access. My only last question is:

When you say "If you add a Faction item to the actor, it will use the name of that Item. It won't be an input anymore, and you can delete the item with the X next to it."

What is the "proper" way to do this instead of entering a String? Once that's answered we're good to go. TIA!

**Comment by moo-man** [comment]
Sounds good, note that the Starter Set module requires V12, if you are considering buying that you may want to wait. 

To add Items to an Actor (in almost every system on Foundry) you just need to drag and drop the Item from the Compendium or World.

**Comment by aaron-bigadventurecrew** [comment]
Where at in your Compendium though? And we'll wait on the Starter Set (but not opposed) because we're hitting the ground running come Sunday. But we're a technically adept group so willing to demo stuff for y'all for the cause.

![patron_faction](https://github.com/user-attachments/assets/841fa135-d61b-43b3-8e00-36b54295ed06)

**Comment by moo-man** [comment]
Items (Core Rulebook) -> Factions folder has Items for each Faction, you'd drag that to the Patron and any Character with that faction. 

If you have Discord, my server (see the Readme) is better for back and forth discussion, if you have more questions.

**Comment by moo-man** [comment]
Adding a Faction will automatically add the associated Influence, I see you have "Influence should be 4." You can't edit the Influence value because it's comprised of sources, which you can add or delete if you click the Faction name in the influence list (I know that's not very clear).
