### ISSUE TITLE
Cannot delete Starting Faction Influence

### ISSUE THREAD

**Issue by Stexinator** [moo-man/ImpMal-FoundryVTT#48]
**Describe the bug**
Cannot delete Influence, this is for example important for homebrew changes or Astra Telepathica

**To Reproduce**
- Have a character with his faction influence
- Try to delete it

**Screenshots**
![grafik](https://github.com/user-attachments/assets/d9510873-c7b3-40fa-b0b0-0a64f917ffbc)

**Version Numbers**
ImpMal 2.0.4

**Comment by moo-man** [comment]
It is tied to the faction item, this is intended

**Comment by Stexinator** [comment]
![grafik](https://github.com/user-attachments/assets/d9d43bbd-b05a-4e09-bd93-e84b2d86bbc6)

How should this be done?
