### ISSUE TITLE
Link of injury broken

### ISSUE THREAD

**Issue by Stexinator** [moo-man/ImpMal-FoundryVTT#52]
**Describe the bug**
The text output of critical injuries has broken links

**To Reproduce**
apply enough damage to create a critical injury

**Screenshots**
![grafik](https://github.com/user-attachments/assets/4da75906-78fb-40f7-a228-1100831c44e1)

**Version Numbers**
2.0.4.

**Comment by moo-man** [comment]
Do you have the core rulebook initialized?

**Comment by Stexinator** [comment]
Yes, I had. I re-intialized and it some conflicts where I said it should take the new version. Now the links work and the effects are applied
