### ISSUE TITLE
Add roll buttons for injuries with rolls

### ISSUE THREAD

**Issue by Stexinator** [moo-man/ImpMal-FoundryVTT#54]
**Is your feature request related to a problem? Please describe.**
The injury calls for a test 

**Describe the solution you'd like**
I want to roll the test from the chat card

**Additional context**
![grafik](https://github.com/user-attachments/assets/036785f3-b8bc-4b38-b530-6f4534a2ccf0)

**Comment by Stexinator** [comment]
I dont understand the suggest solution. This injury comes from damage overflow of an attack. Where in the workflow should I have been promted to roll the Fortitude(Pain) test?

**Comment by Stexinator** [comment]
![grafik](https://github.com/user-attachments/assets/083bb8c5-8a6b-49f0-b039-941e2fe5cc93)

The whole thing for maybe better understanding

**Comment by moo-man** [comment]
The test would be called for when the item is added to the actor, so it would use either an `Immediate` script or `On Create`. 

But regardless, this should already be configured on that Item.

**Comment by moo-man** [comment]
Yes, when an item is "posted" to chat, it can be dragged off chat like normal items.
