### ISSUE TITLE
Apply status effect from injuries

### ISSUE THREAD

**Issue by Stexinator** [moo-man/ImpMal-FoundryVTT#55]
**Is your feature request related to a problem? Please describe.**
Injuries can apply status effects

**Describe the solution you'd like**
I want to apply the status effects from the chat card

**Additional context**
![grafik](https://github.com/user-attachments/assets/309b2d9b-b968-4144-923c-9fa839f71f17)

**Comment by moo-man** [comment]
If by status effects you mean conditions, this is also done via scripts
