### ISSUE TITLE
Bleeding effect not ignoring armour

### ISSUE THREAD

**Issue by Loveablechap** [moo-man/ImpMal-FoundryVTT#6]
**Describe the bug**
The Bleeding minor effect, which cause 1pt of damage after turn has finished is meant to ignore armour. It does not. Script for effect seems correct to me, but I am a novice.

**Comment by moo-man** [comment]
I can't seem to reproduce this: 
![image](https://github.com/moo-man/ImpMal-FoundryVTT/assets/28637157/d3b15f0a-5939-4331-84b3-6260f2b9a5d5)

Do you have a screenshot of what you're seeing?

**Comment by Loveablechap** [comment]
I have just tried to reproduce it from last night and have come to realisation, that the actor in question was at his wound maximum. I will be sure to triple check before posting an issue again. Sorry for wasting time :)

**Comment by moo-man** [comment]
No worries, confuses me too sometimes
