### ISSUE TITLE
Showing damage on a weapon roll

### ISSUE THREAD

**Issue by ArtySemenov** [moo-man/ImpMal-FoundryVTT#8]
**Is your feature request related to a problem? Please describe.**
I'm super frustrated when I roll attack on my Lasgun and it shows the success level but won't show the damage. I always need to do mental maths to figure out that the damage is 6+SL = 6+2 = 8.

**Describe the solution you'd like**
The damage should be shown in the card
There should be an option (like in the demo) to apply damage to selected tokens

**Additional context**

![image](https://github.com/moo-man/ImpMal-FoundryVTT/assets/29398643/d488ba61-52c3-4675-a99d-77a3688cf5c9)

**Comment by moo-man** [comment]
Assuming this is resolved
